In [1]:
from scipy.linalg import logm, expm
import numpy as np

In [2]:
x = np.array([[0.433,0.1768,0.8839,1],[0.25,0.9186,-0.3062,1],[-0.866,0.3536,0.3536,0],[0,0,0,1]])
x

array([[ 0.433 ,  0.1768,  0.8839,  1.    ],
       [ 0.25  ,  0.9186, -0.3062,  1.    ],
       [-0.866 ,  0.3536,  0.3536,  0.    ],
       [ 0.    ,  0.    ,  0.    ,  1.    ]])

In [3]:
y = np.array([[0.75,0.1768,0.8839,2],[0.433,0.9186,-0.3062,4],[-0.5,0.3536,0.3536,3],[0,0,0,1]])
y

array([[ 0.75  ,  0.1768,  0.8839,  2.    ],
       [ 0.433 ,  0.9186, -0.3062,  4.    ],
       [-0.5   ,  0.3536,  0.3536,  3.    ],
       [ 0.    ,  0.    ,  0.    ,  1.    ]])

In [4]:
x@expm(0.5*logm(np.linalg.inv(x)@y))

array([[ 0.59719539,  0.1768    ,  0.8839    ,  1.56017063],
       [ 0.34478787,  0.9186    , -0.3062    ,  2.53473573],
       [-0.67642425,  0.3536    ,  0.3536    ,  1.56947145],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])