In [1]:
import numpy as np

In [2]:
op1 = np.array([2,3,-3])
op2 = np.array([0,0,-3])
op3 = np.array([-1,-2,2])
op4 = np.array([-1,0,-2])

objectArray = [op1,op2,op3,op4]

sp1 = np.array([-1.384, 4.562,-0.128])
sp2 = np.array([-.9608, 1.311,-1.628])
sp3 = np.array([1.325,-2.389,1.702])
sp4 = np.array([-1.314,0.2501,-0.762])

cameraArray = [sp1,sp2,sp3,sp4]

In [3]:
objectCenter = (op1+op2+op3+op4)/4
cameraCenter = (sp1+sp2+sp3+sp4)/4

In [4]:
objectCenter

array([ 0.  ,  0.25, -1.5 ])

In [5]:
cameraCenter

array([-0.58345 ,  0.933525, -0.204   ])

In [6]:
translation = objectCenter - cameraCenter
translation

array([ 0.58345 , -0.683525, -1.296   ])

In [7]:
adjustedObject = []
for point in objectArray:
    adjustedObject.append(point-objectCenter)

adjustedObject

[array([ 2.  ,  2.75, -1.5 ]),
 array([ 0.  , -0.25, -1.5 ]),
 array([-1.  , -2.25,  3.5 ]),
 array([-1.  , -0.25, -0.5 ])]

In [8]:
adjustedCamera = []
for point in cameraArray:
    adjustedCamera.append(point-cameraCenter)

adjustedCamera

[array([-0.80055 ,  3.628475,  0.076   ]),
 array([-0.37735 ,  0.377475, -1.424   ]),
 array([ 1.90845 , -3.322525,  1.906   ]),
 array([-0.73055 , -0.683425, -0.558   ])]

In [9]:
objectPoints = np.array([[2,3,-3,1],[0,0,-3,1],[-1,-2,2,1],[-1,0,-2,1]])
objectPoints

array([[ 2,  3, -3,  1],
       [ 0,  0, -3,  1],
       [-1, -2,  2,  1],
       [-1,  0, -2,  1]])

In [10]:
cameraXpoints = np.array([-1.384,-.9608,1.325,-1.314])
cameraYpoints = np.array([4.5620,1.311,-2.389,0.2501])
cameraZpoints = np.array([-0.1280,-1.6280,1.7020,-0.7620])

In [11]:
rotationArrayX = np.linalg.inv(objectPoints)@cameraXpoints
rotationArrayX

array([ 0.7068125, -0.612275 ,  0.3536125,  0.1000375])

In [12]:
rotationArrayY = np.linalg.inv(objectPoints)@cameraYpoints
rotationArrayY

array([ 0.70721875,  0.6121875 , -0.35368125,  0.24995625])

In [14]:
rotationArrayZ = np.linalg.inv(objectPoints)@cameraZpoints
rotationArrayZ

array([2.22044605e-16, 5.00000000e-01, 8.66000000e-01, 9.70000000e-01])

In [16]:
np.sqrt(0.58345*0.58345+0.683525*0.683525+1.296*1.296)


1.5770974377396598

In [17]:
np.sqrt(0.1*0.1+0.25*0.25+0.97*0.97)

1.006677704133751

In [19]:
rotationMatrix = np.array([[0.706,-0.6123,0.3536],[0.7072,0.6122,-0.3537],[0,0.5,0.866]])
translationMatrix = np.array([0.1,0.25,0.97])

rotationMatrix@op1+translationMatrix

array([-1.3857,  4.5621, -0.128 ])